### ISSUE TITLE
Complete TODO in generateDistricts(); in Redistrictor.java #22 from MetroCS Repo

### ISSUE THREAD

**Issue by JonathanGrant92** [ScrumDogMillionaires/redistricting#1]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  user 
**I want**  the TODO in generateDistricts() in Redistrictor.java to be completed
**so that**  the program can distinguish contiguity of a district.

## Acceptance Criteria

- [ ] Documentation is concise and follows Javadoc format.
- [ ] Method generateDistricts() distinguishes borders of a district.

_**Scenario 1**_  
**Given**  The region to be redistricted and the number of districts for the region
**when**  the program runs  
**then**  it will create a set of properly-contiguous districts matching the parameters.

## Supporting Information
Refer to Redistrictor.java method generateDistricts()

### Depends On
N/A
### Dependents
N/A
